### ISSUE TITLE
Tikz preview not working

### ISSUE THREAD

**Issue by PierreMarchand20** [tecosaur/LaTeX-Utilities#13]
### Disable all the other extensions except for LaTeX Workshop and LaTeX Utilities, and check that you still see this issue.

You still see this issue?: Yes

### Describe the bug

The following Tikz picture does not work, there is an issue with the size of the picture.
```
% !TeX encoding =UTF-8 Unicode
\documentclass[tikz]{standalone}
\usepackage{tikz-qtree}
\tikzset{grow'=down}

\begin{document}
    \begin{standalone}
        \begin{tikzpicture}[level distance=30pt,
                            sibling distance=10pt,
                            every tree node/.style={draw,circle,inner sep=0pt,minimum size=3pt},
                            edge from parent path={(\tikzparentnode) -- (\tikzchildnode)},
                            ]
            \Tree   [. \node[label=above:1] {}; 
                        \edge node[auto=left,pos=.6] {$B$};
                            [. \node[fill=black,label=below:{3,3}] {}; ]
                        \edge node[auto=right,pos=.6] {$A$};
                            [.\node[fill=black,label=above left:2] {}; 
                                \edge node[auto=left,pos=.6] {$D$};
                                    [.\node[fill=black,label=below:{1,1}] {}; ]
                                \edge node[auto=right,pos=.6] {$C$};
                                [.\node[fill=black,label=above left:1] {}; 
                                \edge node[auto=left,pos=.6] {$F$};
                                    [.\node[fill=black,label=below:{2,2}] {}; ]
                                \edge node[auto=right,pos=.6] {$E$};
                                    [.\node[fill=black,label=above left:2] {}; ] 
                                ]
                            ]
                    ]     
        \end{tikzpicture}   
    \end{standalone}
\end{document}
```

### To Reproduce

Steps to reproduce the behaviour:

1. Take the previous example.

### Screenshots

![image](https://user-images.githubusercontent.com/15056323/63580420-0ec37400-c595-11e9-8c02-b24e9cfb76c9.png)

### Desktop

-   OS: 10.14.6
-   VS Code version: 1.37.1
-   Extension version: 0.2.1

**Comment by joulev** [comment]
It is because this is a Ti*k*Z preview, not a `tikz-qtree` preview. `tikz-qtree` is an extension of `tikz`, so Ti*k*Z features are included in `tikz-qtree`, but not all `tikz-qtree` features are present in Ti*k*Z. The same output will appear if you delete `\usepackage{tikz-qtree}`. So, put simply, it is a compilation error.

If you go to the source of the preview file, the preamble will look like this

```latex
\documentclass{standalone}


\usepackage{tikz}

\tikzset{grow'=down}

\pdfcompresslevel=0
\pdfobjcompresslevel=0
```

No `tikz-qtree`. In fact, `tikz-qtree` is only considered an external package, not related to anything in the preview.

Many many packages load Ti*k*Z and use `tikzpicture` environment. To make the preview work in these cases, we have to include all Ti*k*Z-related packages in the preamble, which the current version of LaTeX Utilities doesn't do yet.

---

Here, as a user, I think we have to do one of the following:

* Include all Ti*k*Z-related packages in the preamble, or in short, include all packages in the preamble (Ti*k*Z is very popular, you know). This will make cases like this work well, but the compilation time is much longer.
* Write to `README` the following line: "The Ti*k*Z preview only works for Ti*k*Z pictures that don't include any macros defined by any external packages."

**Comment by joulev** [comment]
@PierreMarchand20 (This comment is off topic) If you have used `standalone` class, you don't have to use `standalone` environment.

**Comment by PierreMarchand20** [comment]
> @PierreMarchand20 (This comment is off topic) If you have used `standalone` class, you don't have to use `standalone` environment.

My bad ^^

**Comment by PierreMarchand20** [comment]
> It is because this is a Ti_k_Z preview, not a `tikz-qtree` preview. `tikz-qtree` is an extension of `tikz`, so Ti_k_Z features are included in `tikz-qtree`, but not all `tikz-qtree` features are present in Ti_k_Z. The same output will appear if you delete `\usepackage{tikz-qtree}`. So, put simply, it is a compilation error.
> 
> If you go to the source of the preview file, the preamble will look like this
> 
> ```
> \documentclass{standalone}
> 
> 
> \usepackage{tikz}
> 
> \tikzset{grow'=down}
> 
> \pdfcompresslevel=0
> \pdfobjcompresslevel=0
> ```
> 
> No `tikz-qtree`. In fact, `tikz-qtree` is only considered an external package, not related to anything in the preview.
> 
> Many many packages load Ti_k_Z and use `tikzpicture` environment. To make the preview work in these cases, we have to include all Ti_k_Z-related packages in the preamble, which the current version of LaTeX Utilities doesn't do yet.
> 
> Here, as a user, I think we have to do one of the following:
> 
> * Include all Ti_k_Z-related packages in the preamble, or in short, include all packages in the preamble (Ti_k_Z is very popular, you know). This will make cases like this work well, but the compilation time is much longer.
> * Write to `README` the following line: "The Ti_k_Z preview only works for Ti_k_Z pictures that don't include any macros defined by any external packages."

We could also parse the file where Tikz-preview is called to add any Tikz-related packages no ?

**Comment by PierreMarchand20** [comment]
There are some many `tikz-*` that it could be useful.

**Comment by PierreMarchand20** [comment]
Is there a similar issue with all the sub packages `\usetikzlibrary` ?

**Comment by joulev** [comment]
Normal libraries are okay, but libraries like `duck` or `hobby` don't work because they are external libraries.

In short, everything you can find in https://github.com/pgf-tikz/pgf works well and every other thing does not.

**Comment by joulev** [comment]
I advise against including any external packages/libraries.

Why? It will take very long to compile.

Not only packages like `tikz-*` are Ti*k*Z-related. `hobby`, `tikzducks`, `tikzlings`, `tcolorbox`, etc. are also counted. And local packages... and etc. etc. etc...

There are just too many. There is almost no way to decide what package to include. We can only include everything, which is definitely out of the question.

**Comment by PierreMarchand20** [comment]
I agree that it would be too much to add everything by default, but parse the original file to find out if another package needs to be added seems ok. Then you just need to know which library to look for.

**Comment by PierreMarchand20** [comment]
Anyway, it answers my issue so I close it ^^

**Comment by joulev** [comment]
@PierreMarchand20 Oh no, anyway I am not the author of the extension, just a user of it. I think we should wait @tecosaur before closing anything.

**Comment by tecosaur** [comment]
@joulev thanks for helping with this. @PierreMarchand20 I concur with joulev that including the entire preamble would introduce significant performance issues compared to the current implementation, for no gain (for _most_ users). However, something that probably wouldn't be too hard would be to add a togglable setting to switch to including the _entire_ preamble.

**Comment by PierreMarchand20** [comment]
As I said, I agree that including the whole preamble does not make sense.

But you could just copy paste the additional TikZ related packages from the original file to the preview file.

**Comment by tecosaur** [comment]
> But you could just copy paste the additional TikZ related packages from the original file to the preview file.

The current method attempts to determine relevant lines in the preamble, 'just copy paste' isn't really a viable option. If you have packages which you use that affect the TikZ preview, you will probably be interested in the `latex-utilities.tikzpreview.preambleContents` setting.

`package.json — latex-utilities.tikzpreview.preambleContents`
> Set the path of a file containing LaTeX code to be included in the preamble of standalone documents for tikzpicture preview. If the path is relative, it is joined with the root dir.

Actually, I almost forgot about that setting. Since it does exist I think that provides a reasonable method to cope with unusual required packages etc.

**Comment by PierreMarchand20** [comment]
Yes prefect !
