### ISSUE TITLE
Character count

### ISSUE THREAD

**Issue by SPAstef** [tecosaur/LaTeX-Utilities#159]
Is it possible to get a character count, alongside the word count?

**Comment by tecosaur** [comment]
Quite possibly. All this extension does is call, and parse the output of `texcount`. Anything that can do, this extension should be able to (with appropriate tweaking) tell you about.

I'm afraid that due to me moving to another editor I'm no longer maintaining this extension :slightly_frowning_face: (sorry to disappoint), but don't let that from stop you from making this happen :slightly_smiling_face:.

I strongly encourage you to take a peek at this extension's code, then give implementing it a shot! If your experience is anything like mine, this will be way easier than you expect :smiley:

I'd happily answer questions on the internals of this extension, and I'd be thrilled to accept a PR on this.

**Comment by SPAstef** [comment]
So, I am graduating like next month in CS, and I started using latex really just a couple weeks ago to write my thesis, and have no experience with VS Code extensions (I know very well C, I'm decent at Java, PHP and Bash). Anyway, since you are so kind, if I have time I will gladly give a peek here and there. I have been able to get character count, but not both (this is a limitation of TexCount, it would require 2 calls to get both, at least that's what I understood reading the docs)

**Comment by tecosaur** [comment]
@SPAstef if you can implement this, that would be marvelous :) I'd be happy to help out here and there.

**Comment by SPAstef** [comment]
@tecosaur your extension is really awesome, I always used VScode and changing environment is always a struggle (also 90% of editors are ugly and don't have intellisense). When I get some time, I will certainly give it a look!

**Comment by dbourrion** [comment]
Hi. That command line looks working in a Linux terminal `texcount -char -sum -1 the_file.tex` but I have no idea how to put this in a VSC extension :(

**Comment by leoleoasd** [comment]
I believe this is fixed. You can click on the word count on the status bar, and select character count:

<img width="458" alt="image" src="https://github.com/tecosaur/LaTeX-Utilities/assets/37735580/65e36099-b83a-4e89-ab7e-771e194f7a6d">
