### ISSUE TITLE
Port functionality to LaTeX workshop?

### ISSUE THREAD

**Issue by janosh** [tecosaur/LaTeX-Utilities#209]
Just saw the note that this repo will no longer be maintained. 😢 

> ### ⚠️ Warning — looking for a maintainer
> 
> **This extension is no longer maintained.** I'm sorry, it's not you, it's me. I still love this functionality, I've just moved to a different editor to get it.
> I don't want to leave you in the lurch, but I find it somewhat difficult to spend much time on an extension for an editor I no longer use.
> That said, while I may not be planning on doing any work myself, _I will gladly accept PRs_. New functionality? Bug fix? Don't let me stop you: **PR!**

What do you think of salvaging its functionality over to [LaTeX workshop](https://github.com/James-Yu/LaTeX-Workshop) (if @James-Yu agrees, that is)? Seems like a shame if this was lost, especially the Zotero integration which is a life saver for me!

Also, just out of curiosity, what's that other editor you're now using?

**Comment by tecosaur** [comment]
I wrote this using the same structure as LaTeX workshop, precisely so that it would be easy to move features between the two extensions. If James is interested it should be fairly easy to port the functionality over :smiley:

Regarding my move, you're probably best served by my [earlier response](https://github.com/tecosaur/LaTeX-Utilities/issues/176#issuecomment-632569444) to that question :stuck_out_tongue:

**Comment by janosh** [comment]
@James-Yu Ping

**Comment by tecosaur** [comment]
As this has bee responded to, I'm closing this.
