### ISSUE TITLE
New maintainer?

### ISSUE THREAD

**Issue by leoleoasd** [tecosaur/LaTeX-Utilities#347]
LaTeX-workshop dropped support for this extension (see James-Yu/LaTeX-Workshop#3009). Maybe we should mark this extension unuseable, or remove it from vscode extension marketplace.

**Comment by tecosaur** [comment]
That's a decent idea. I'll see about changing the readme and publishing it as a new version.

**Comment by leoleoasd** [comment]
I just found this extension, and I desperately need its features(formatted pasting, etc.). Maybe I can help maintain this extension after a few weeks (recently I have no time), trying to get support from LaTeX-Workshop, or implement a subset of features without their support (it seems that previewing tikz pictures needs their API, but Zotero support and formated pasting don't).

**Comment by tecosaur** [comment]
If you're interested in maintaining it, that's great! I'd be happy to give you all the access needed. It looks like the main concerns in that issue are around maintenance, so if you become the maintainer of this extension they may well be happy to revert that commit :)

**Comment by leoleoasd** [comment]
Sure! I'll try reverting that commit locally, update this extension to make sure that everything works fine, then reach out to them.

**Comment by tecosaur** [comment]
If you could take a look at the codebase, have a think about it, and let me know whether you really are willing to be the maintainer long-term (i.e. on the scale of months-years not weeks) that would be good.

I'd love for this extension to get the love it (in my very unbiased opinion 😉) deserves, but I wouldn't like to see it just get a short burst of attention and then be re-abandoned or poorly maintained. I don't know you, but I'm willing to make this minor leap of faith, I'd just appreciate it if you could make sure you know what you're signing up for and confirm that you're willing to give it a good shot 🙂.

If you are that would be fantastic. I'm happy to answer the odd question about the code base etc. but unfortunately, I won't have much time to help — you'll largely be on your own.

**Comment by leoleoasd** [comment]
Hi @SirHamburger!
Some of your features seem good to me. In particular:

- Prefix and Suffix for tables
   Sounds good to me. What about a customizable table template?
- Prefix and Suffix for images
   What do you mean by this? I've checked your code, do you mean something like `labelPrefix`?
- Ignore Graphicspath and just drop the image in the current folder
   Yes, this should be an option.
- Temporary save Filepath from clipboard to copy and paste an image name (only windows)
   Do you mean insert an `includegraphics` by pasting a path? 
- Use caption name for formated paste and generate label and image name through the caption name
   In my opinion, we should use the label name as file name instead of the caption, cause in non-english speaking countries, we tend to use ASCII filename but captions in our language.
- Replace the path in a document for only compiling a single file (needs magic root comment)
   What do you mean by this?
- Remove all commands in a document
   Can you demonstrate your usage of this feature?

For some of these features, like a more powerful table template, I'll be happy to implement them if you are not into learning TypeScript, by cleaning and referencing your code and I’ll list you as co-author. 

But, I'm currently focusing on fixing capability issues with Workshop, since they drop the support for this repo. After that let's see what we can do about these features. If you want to use this repo right now, you need to use the `dev` branch of my repo and [my fork of Workshop](https://github.com/leoleoasd/LaTeX-Workshop).

**Comment by SirHamburger** [comment]
Hi @leoleoasd,
* Prefix and Suffix for tables
At the moment you can specify the part which will be inserted before the table and the part after the table. So in my opinion that would be more or less a table template. But maybe i can change it to a full template.
```  
"latex-utilities.formattedPaste.PrefixTableTemplate": "\\begin{table}[H]\n\t\t\\begin{NiceTabular}{",
  "latex-utilities.formattedPaste.SuffixTableTemplate": "\t\t\\end{NiceTabular}\n\t\\caption{}\\n\t\\end{table}",```
* Prefix and Suffix for images
In this case i just added some variables for inserting the image with the caption name and have forgotten about it. That ist completely optional (with settings) but in my case quite handy because we always want the name of the image to be the same name as the caption (but in camel case). In my case generating the caption out of the label name is not possible since i don't want any spaces in the caption name. 
The `labelPrefix` is that you can specify a prefix. But you could also do that in the template.
```  
"latex-utilities.formattedPaste.image.template": "\t\\begin{figure}[H]\n\t\t\\centering{}\n\t\t\\includegraphics[width=\\textwidth]{${imageFilePath}}\n\t\t\\caption{${imageCaption}}\\label{${imageLabel}}\t\n\t\\end{figure}",```
* Ignore Graphicspath and just drop the image in the current folder
Latex Workshop had some issues with calculating the Graphicspath if you use import. If you not use import the calculated path would be better.
* Temporary save Filepath from clipboard to copy and paste an image name (only windows)
There are two possibilities how to copy and paste. The first is you make a screenshot with e.g. Snipping tool and directly paste it. The second is you copy a file in the clipboard. In the second case you can copy the name of the file or the caption while you're inserting the image. So i changed the menu to always be visible and save the path.
* Use caption name for formatted paste and generate label and image name through the caption name
See "Prefix and Suffix for images"
* Replace the path in a document for only compiling a single file (needs magic root comment)
We have documents with several hundert pages. So if you're writing at one chapter you only want to compile this chapter (like \includeonly but without the dependency to include). For that we have a file with the name buildOnly.tex which reads the labels of the main documents but only builds one chapter. Since you've to always replace the import i wrote a command which does this automaticly if the root comment is buildOnly and the markers are set. If you want i can make an example project.
* Remove all commands in a document (section)
If you've a text with commands you can mark the text and remove all commands in it. I used it to reset all highlighting (like \textbf or \textit)

In theory all changes should not affect any of the current functionality. Everything is optional by settings or a new command.

If you want all these features i can change the table to a template but for the refactoring i maybe need some help since i don't know what your target coding style is.

Also i think the fix of the current features is more important.

**Comment by leoleoasd** [comment]
First,  I'll fix the current features.
Then, you can open a Pull Request. Due to large modifications to the codebase to fix current features, you may need to refactor the current code, and I can provide the necessary help. If you aren't into this, you can open a pull request with `allow modifications from author` and let me do this job.

**Comment by leoleoasd** [comment]
New version is published and ready-to-use!
